### PR TITLE
Apply scroll resolution

### PR DESCRIPTION
**Pull request by gimdh**
I applied suggested code snippet in #22 and it feels a little smoother. Not sure if it's as good as VoodooPS2's implementation, though.

I found VoodooI2C development chat suggesting 2300 could be better than 800, but there was no difference for me. Also, their recent build uses 800 as default, so I opted for 800.

### CODE REVIEW

**Comment by 1Revenger1** [comment]
These values aren't going to affect the trackpoint as RMIBus isn't the IOService sending the values. Need to apply them to ButtonDevice/TrackpointDevice.

Also, we likely don't want to apply trackpad acceleration values to the trackpoint.

**Comment by gimdh** [comment]
Oh I see. There must have been some placebo. I'll place it correctly. 
By the way, VoodooPS2 applies Trackpad acceleration to Trackpoint, doesn't it?

**Comment by 1Revenger1** [comment]
@gimdh did you ever figure out the scroll resolution stuff? Was gonna close this otherwise.

**Comment by gimdh** [comment]
I decided to wait for 1.0 to before any work, and completely forgot about this.
Thank you for reminding. I'll tinker a bit with VoodooTrackpoint to see if it's any better.

**Comment by gimdh** [comment]
I can confirm that code does work, but it's under VoodooTrackpoint's territory since major refactoring.
Closing this PR, and moving to VoodooTrackpoint.

**Pull request closed without merging**
