### PR TITLE
Term cleanup, touch up readme

### LINKED ISSUE #39: Minor] Terminology cleanup
I would like to make following changes

* That tiny pointer thingy we all love
HP, Dell, and others use 'Pointer stick'/'Pointing stick'/'Point stick' as a general term, while Lenovo uses trademarked 'TrackPoint'. Wikipedia uses 'Pointing stick'. 
I think codebase should settle with one of popular terms instead of trackstick.

* Touchpad / Trackpad
Touchpad is general term for flat touch input device. Trackpad is Apple's trademarked counterpart.  I think 'touchpad' fits most cases and can avoid confusion with genuine Apple ones.

### PR DESCRIPTION
**Pull request by gimdh**
Deals #39. Terms replaced are as follows. 

> Touchpad -> Trackpad
> Trackstick -> Trackpoint

1Rev ~ Closes #39

### CODE REVIEW

**Comment by 1Revenger1** [comment]
Have you tested with ioio changing the trackstick parameters (based off the readme) to make sure they still work?
Otherwise looks good to me. Thanks!

**Comment by 1Revenger1** [comment]
Closes #39

**Comment by gimdh** [comment]
I never used ioio before, but all I did was renaming so it should work fine. I'll test it, though.

**Comment by gimdh** [comment]
I have tested with ioio and can change property values online.

**Pull request merged**
