### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LocTran016**
For more detail, you can read here: https://osxlatitude.com/forums/topic/13719-inspiron-3421-synaptic-ps2-trackpad/?tab=comments#comment-102184.

### CODE REVIEW

**Comment by 1Revenger1** [comment]
You could try using an SSDT to set _STA to zero for that PS2 device? Not entirely sure that'd work. It would make it dissapear I think from the IOService plane at least.

```
DefinitionBlock(/* I forget all this */)
  External (\_SB.LPCB.PS2M, DeviceObj) // This may not be the exact path to PS2M

  Scope (\_SB.LPCB.PS2M) { // or whatever the path is
    If (_OSI("Darwin")) {
      _STA = 0x00
    }
  }
}
```

Another alternative you could try doing is changing _HID to be something other than a PS2 device, using something similar to above. I'm gonna test this on my end I guess, and see what I come up with.

That said, I've not needed to do something like this, all I've needed to do is prevent VoodooPS2Mouse/VoodooPS2Trackpad from loading. Setting Enabled to `false` for those in the Config.plist is enough

**Comment by 1Revenger1** [comment]
image

```
DefinitionBlock ("", "SSDT", 2, "GWYD", "PS2M", 0) {
    External (\_SB.PCI0.LPCB.MOU._HID, StrObj)
    External (\_SB.PCI0.LPCB.MOU._CID, StrObj)
    
    If (_OSI("Darwin")) {
        \_SB.PCI0.LPCB.MOouU._HID = EisaId("GWY0000")
        \_SB.PCI0.LPCB.MOU._CID = EisaId("GWY0000")
    }  
}
```

I just whipped this up pretty quickly. Prevents VoodooPS2 from attaching to MOU. Mind trying this?

**Comment by LocTran016** [comment]
I finally got it to work on OpenCore. Didn't have to disable PS2M or MOU. I found a version of VoodooSMBus from [here](https://github.com/EETagent/T480-OpenCore-Hackintosh).
Even though the version numbers are the same as the release version, the code is different. VoodooRMI is the same as the release version, so I'm not sure where that other VoodooSMBus came from.

**Comment by LocTran016** [comment]
Anyway, sorry for this crazy things and well as interrupting you

**Comment by 1Revenger1** [comment]
The version of VoodooSMBus there looks no different than the one in the dev branch in VoodooSMBus (which is what VoodooRMI relies on) 🤔

That is V2.2, and nothing has been changed since it was bumped up to V2.2.
It may be related to build environment maybe?Is there any difference using VoodooSMBus Debug vs Release? I can try clearing my build cache, though I haven't had any issues with the last releases, which should all contain the same version of VoodooSMBus.

**Pull request closed without merging**
