### PR TITLE
Prompt in debug log for mismatched vendor ID

### PR DESCRIPTION
**Pull request by zhen-zen**

### CODE REVIEW

**Comment by zhen-zen** [comment]
Seems like the build broke with https://github.com/acidanthera/VoodooInput/commit/c6f297714669af2701bf8aeaec463829cd50c0bb

**Comment by 1Revenger1** [comment]
Changes look fine. Not exactly sure how I'll deal with the VoodooInput changes tbh, my project sort of depended on the trackpoint device being independent lol.

**Comment by 1Revenger1** [comment]
Do you mind merging in master into this?

**Comment by zhen-zen** [comment]
No, go ahead.

**Pull request merged**
