### PR TITLE
Replace log for input events with IOLogVerbose

### PR DESCRIPTION
**Pull request by zhen-zen**
I'm not sure if I have missed something, maybe asking more people to test it?

### CODE REVIEW

**Comment by zhen-zen** [comment]
The log sounds good on my side:
```
[    0.877892]: VRMI - Debug: RMII2C::TPD0 probing
[    0.878960]: VRMI - Error: RMII2C::TPD0 Could not get valid HID descriptor
[    1.378215]: VRMI - Debug: RMII2C::TPL1 probing
[    1.378270]: VRMI - Debug: RMII2C::SHUB probing
[    1.379127]: VRMI - Debug: RMII2C::TPL1 Trying to set mode, attempt 0
[    1.379399]: VRMI - Info: RMII2C::TPL1 reset completed
[    1.386344]: VRMI - Error: RMII2C::SHUB Could not get valid HID descriptor
[    1.881326]: VRMI - Debug: Config TrackpointMultiplier loaded: a -> a
[    1.881331]: VRMI - Debug: Config TrackpointScrollMultiplierX loaded: a -> 1e
[    1.881334]: VRMI - Debug: Config TrackpointScrollMultiplierY loaded: a -> 1e
[    1.881337]: VRMI - Debug: Config TrackpointDeadzone loaded: 1 -> 1
[    1.881340]: VRMI - Debug: Config DisableWhileTypingTimeout loaded: 1f4 -> 64
[    1.881343]: VRMI - Debug: Config DisableWhileTrackpointTimeout loaded: 1f4 -> 64
[    1.881346]: VRMI - Debug: Config ForceTouchMinPressure loaded: 50 -> 5a
[    1.881349]: VRMI - Debug: Config ForceTouchEmulation loaded: 1 -> 1
[    1.881352]: VRMI - Debug: Config MinYDiffThumbDetection loaded: c8 -> c8
[    1.881354]: VRMI - Debug: Updating Configuration
[    1.881362]: VRMI - Info: RMI Bus (DEBUG) Starting up!
[    1.881420]: VRMI - Debug: RMII2C::TPL1 powerState 1 : on
[    1.882834]: VRMI - Info: RMII2C::TPL1 reset completed
[    1.883257]: VRMI - Debug: rmi_probe_interrupts: Counting IRQs
[    1.893365]: VRMI - Debug: IRQ Count: 8
[    1.893465]: VRMI - Debug: rmi_init_functions: Creating functions
[    1.894535]: VRMI - Info: Initializing F34.
[    1.894543]: VRMI - Debug: Function F34 - IRQs: 1 CMD Base: 0 CTRL Base: 17 DATA Base: 0 QRY Base: 37 VER: 2
[    1.894546]: VRMI - Info: F34 not implemented
[    1.895261]: VRMI - Info: Initializing F01.
[    1.895264]: VRMI - Debug: Function F1 - IRQs: 2 CMD Base: 36 CTRL Base: 18 DATA Base: 6 QRY Base: 45 VER: 0
[    1.900762]: VRMI - Info: Found RMI4 device, manufacturer: Synaptics, product: TM3390-001, fw id: 2735754
[    1.903090]: VRMI - Info: Initializing F12.
[    1.903098]: VRMI - Debug: Function F12 - IRQs: 2 CMD Base: 0 CTRL Base: 25 DATA Base: 11 QRY Base: 77 VER: 0
[    1.906088]: VRMI - Debug: F12 - reg: 0 reg size: 1 subpackets: 1
[    1.906095]: VRMI - Debug: F12 - reg: 1 reg size: 1 subpackets: 1
[    1.906099]: VRMI - Debug: F12 - reg: 2 reg size: 3 subpackets: 2
[    1.906104]: VRMI - Debug: F12 - reg: 3 reg size: 40 subpackets: 12
[    1.906108]: VRMI - Debug: F12 - reg: 4 reg size: 1 subpackets: 1
[    1.906112]: VRMI - Debug: F12 - reg: 5 reg size: 10 subpackets: 2
[    1.906117]: VRMI - Debug: F12 - reg: 6 reg size: 26 subpackets: 11
[    1.906120]: VRMI - Debug: F12 - reg: 7 reg size: 1 subpackets: 1
[    1.906124]: VRMI - Debug: F12 - reg: 8 reg size: 6 subpackets: 2
[    1.906128]: VRMI - Debug: F12 - reg: 9 reg size: 12 subpackets: 6
[    1.906132]: VRMI - Debug: F12 - reg: 10 reg size: 2 subpackets: 2
[    1.906136]: VRMI - Debug: F12 - reg: 13 reg size: 1 subpackets: 1
[    1.908454]: VRMI - Debug: F12 - reg: 8 reg size: 15 subpackets: 5
[    1.908461]: VRMI - Debug: F12 - reg: 9 reg size: 20 subpackets: 5
[    1.908465]: VRMI - Debug: F12 - reg: 10 reg size: 19 subpackets: 5
[    1.908468]: VRMI - Debug: F12 - reg: 11 reg size: 22 subpackets: 6
[    1.908472]: VRMI - Debug: F12 - reg: 15 reg size: 7 subpackets: 3
[    1.908476]: VRMI - Debug: F12 - reg: 19 reg size: 67 subpackets: 5
[    1.908479]: VRMI - Debug: F12 - reg: 20 reg size: 1 subpackets: 1
[    1.908482]: VRMI - Debug: F12 - reg: 22 reg size: 4 subpackets: 2
[    1.908485]: VRMI - Debug: F12 - reg: 23 reg size: 3 subpackets: 3
[    1.908489]: VRMI - Debug: F12 - reg: 28 reg size: 1 subpackets: 1
[    1.908492]: VRMI - Debug: F12 - reg: 69 reg size: 8 subpackets: 1
[    1.910204]: VRMI - Debug: F12 - reg: 1 reg size: 40 subpackets: 5
[    1.910210]: VRMI - Debug: F12 - reg: 2 reg size: 1 subpackets: 1
[    1.910214]: VRMI - Debug: F12 - reg: 4 reg size: 1 subpackets: 1
[    1.910217]: VRMI - Debug: F12 - reg: 5 reg size: 15 subpackets: 5
[    1.910221]: VRMI - Debug: F12 - reg: 9 reg size: 10 subpackets: 5
[    1.910224]: VRMI - Debug: F12 - reg: 15 reg size: 1 subpackets: 1
[    1.910228]: VRMI - Debug: F12 - Data packet size: 68
[    1.911098]: VRMI - Debug: F12 - Number of fingers 5
[    1.912509]: VRMI - Info: Initializing F54.
[    1.912516]: VRMI - Debug: Function F54 - IRQs: 1 CMD Base: 322 CTRL Base: 272 DATA Base: 256 QRY Base: 323 VER: 0
[    1.912523]: VRMI - Info: F54 not implemented
[    1.913877]: VRMI - Info: Initializing F30.
[    1.913881]: VRMI - Debug: Function F30 - IRQs: 1 CMD Base: 512 CTRL Base: 513 DATA Base: 512 QRY Base: 519 VER: 0
[    1.914908]: VRMI - Debug: F30: Found Button 1
[    1.916312]: VRMI - Info: Initializing F55.
[    1.916315]: VRMI - Debug: Function F55 - IRQs: 1 CMD Base: 773 CTRL Base: 768 DATA Base: 768 QRY Base: 774 VER: 0
[    1.916321]: VRMI - Info: F55 not implemented
[  561.390318]: VRMI - Debug: Sleep
[  561.391615]: VRMI - Debug: RMII2C::TPL1 powerState 0 : off
[ 1817.079531]: VRMI - Debug: RMII2C::TPL1 powerState 1 : on
[ 1818.080737]: VRMI - Debug: Wakeup
[ 1818.081185]: VRMI - Info: RMII2C::TPL1 reset completed
[ 1818.081799]: VRMI - Debug: Function F34 found again
[ 1818.082417]: VRMI - Debug: Function F1 found again
[ 1818.083050]: VRMI - Debug: Function F12 found again
[ 1818.084631]: VRMI - Debug: Function F54 found again
[ 1818.086077]: VRMI - Debug: Function F30 found again
[ 1818.087546]: VRMI - Debug: Function F55 found again
[ 1866.364368]: VRMI - Debug: Sleep
[ 1866.366481]: VRMI - Debug: RMII2C::TPL1 powerState 0 : off
[ 2851.995266]: VRMI - Debug: RMII2C::TPL1 powerState 1 : on
[ 2852.996632]: VRMI - Debug: Wakeup
[ 2852.997070]: VRMI - Info: RMII2C::TPL1 reset completed
[ 2852.997765]: VRMI - Debug: Function F34 found again
[ 2852.998441]: VRMI - Debug: Function F1 found again
[ 2852.999166]: VRMI - Debug: Function F12 found again
[ 2853.000797]: VRMI - Debug: Function F54 found again
[ 2853.002699]: VRMI - Debug: Function F30 found again
[ 2853.004640]: VRMI - Debug: Function F55 found again
```

**Comment by 1Revenger1** [comment]
I think having a seperate variable for debug logging while also having a debug version is a little weird. I think this was in response to an issue I was having with Big Sur, and not being able to get logs with `log` (works with `dmesg` though). Still not really sure what's up with that, but this PR doesn't fix this.

**Comment by zhen-zen** [comment]
I suppose all kexts injected with bootloader won't get anything from `log`. So I'm not sure if there would be some kind of solutions. The purpose of this PR is just to get rid of overwhelming logs even on debug builds since touch events flood much more info.

**Comment by 1Revenger1** [comment]
imo - generally you are going to be using the debug version for the touch information. It doesn't provide a ton of extra information about the initialization. I suppose it might be a bit more info in RMII2C?
The release build should be used in any setting where you aren't debugging, as I see significantly less CPU usage on my system at least. Part of it probably does come from the logging tbh. Actually I'm sort of curious now what debug CPU usage is without logging...

**Comment by zhen-zen** [comment]
Yes, I just realized that point. Debug version is just for temporary use. Maybe got a bit spoiled by how Lilu DBGLOG works.

**Pull request closed without merging**
